sudo: required

services:
  - docker

script:
  - docker build -t jaschweder/php:cli .

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jaschweder/php:5.6;
